[project]
name = "agentic-design-patterns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sandip Samantaray", email = "samantaray.sandip@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "openai>=2.38.0",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
]

[project.scripts]
agentic-design-patterns = "agentic_design_patterns:main"

[build-system]
requires = ["uv_build>=0.11.15,<0.12.0"]
build-backend = "uv_build"
